global using Medication_Reminder_API.Enums;
global using Medication_Reminder_API.Models;
global using Medication_Reminder_API.DTOS;
global using Microsoft.EntityFrameworkCore;
global using FluentValidation;
global using AutoMapper;
global using Medication_Reminder_API.Services.Interfaces;
global using Microsoft.AspNetCore.Mvc;
global using System.Security.Claims;